import requests
from datetime import datetime, timedelta
import pytz

# GitHub 사용자 이름 설정
username = 'baegyutae'

# GitHub API를 통해 이벤트 가져오기
url = f'https://api.github.com/users/{username}/events'
headers = {'Accept': 'application/vnd.github.v3+json'}
response = requests.get(url, headers=headers)
events = response.json()

# 현재 시각을 UTC로 설정
now = datetime.now(pytz.utc)

# 연속 커밋 일수 계산
streak = 0
for i in range(365): # 최대 365일 동안 검사
    # 검사할 날짜 (오늘부터 거슬러 올라감)
    check_date = now - timedelta(days=i)
    commit_found = False
    
    for event in events:
        # 이벤트 타입이 PushEvent이고, 해당 날짜에 맞는지 확인
        if event['type'] == 'PushEvent':
            # 이벤트 날짜 파싱
            event_date = datetime.strptime(event['created_at'], '%Y-%m-%dT%H:%M:%SZ')
            event_date = event_date.replace(tzinfo=pytz.utc)
            
            # 이벤트 날짜가 검사 날짜와 같은지 확인
            if event_date.date() == check_date.date():
                commit_found = True
                break
    
    if commit_found:
        streak += 1
    else:
        break

print(f'연속 커밋 일수: {streak}')
